title: Control Notes
description: Process Control Notes
theme: minima
header_pages:
  - index.md
markdown: kramdown
kramdown:
  math_engine: mathjax
github_username: ProcessControlNotes
# email: mark29464@gmail.com
